username: pedrojosawczuk

guid: '1000'
timezone: 'America/Sao_Paulo'

themes: 'ghcr.io/gilbn/theme.park'
tptheme: 'overseerr'
#tptheme: 'organizr'

traefik_network: 'proxy'

config_folder: '/media/Archives/sawczukserver/selfhosted'
home_folder: '/home/pedrojosawczuk'
home_folder_linux: '/media/Archives/sawczukserver'
media_folder: '/media/Archives/media'