---
- name: Ensure all Necessary Groups are Created
  groups:
    name: "{{ item }}"
  loop:
    - "{{ username }}"
    - docker

- name: Ensure the Non-root user ir Created
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    groups:
      - sudo
      - docker
      - users
    append: yes
    shell: "{{ shell }}"
    update_password: on_create

- name: Enable Passwordless Sudo for {{ username }}
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Supress Login Message (hushlogin)
  file:
    path: "/home/{{ username }}/.hushlogin"
    mode: 0644
    owner: "{{ username }}"
    group: "{{ username }}"
    modification_time: preserve
    access_time: preserve
    state: touch