- name: Update Packages (Debian-Based)
  apt:
    update_cache: yes
    upgrade: yes

- name: Install Essential Packages
  package:
    name: '{{ list_of_packages }}'
    state: present

- name: Enable Passwordless Sudo for {{ username }}
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"