# Deploy Duplicati
# ----------------
- name: Deploy Duplicati
  community.docker.docker_container:
    name: duplicati
    image: 'lscr.io/linuxserver/duplicati:2.0.7'
    env:
      'PUID': '0'
      'PGID': '0'
      'TZ': '{{ timezone }}'
      'DOCKER_MODS': '{{ themes }}:duplicati'
      'TP_THEME': '{{ tptheme }}'
    volumes:
      - '{{ config_folder }}/duplicati:/config'
      - '{{ config_folder }}:/source/selfhosted'
      #- '{{ home_folder_linux }}/Nextcloud/swczk/files:/source/nextcloud'
      - '{{ home_folder }}:/source/homefolder'
      - '{{ media_folder }}/backups:/backups'
    networks:
      - name: '{{ traefik_network }}'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.duplicati.entrypoints: 'http'
      traefik.http.routers.duplicati.rule: 'Host(`duplicati.docker.localhost`)'
      traefik.http.middlewares.duplicati-https-redirect.redirectscheme.scheme: 'https'
      traefik.http.routers.duplicati.middlewares: 'duplicati-https-redirect'
      traefik.http.routers.duplicati-secure.entrypoints: 'https'
      traefik.http.routers.duplicati-secure.rule: 'Host(`duplicati.docker.localhost`)'
      traefik.http.routers.duplicati-secure.tls: 'true'
      traefik.http.routers.duplicati-secure.service: 'duplicati'
      traefik.http.services.duplicati.loadbalancer.server.port: '8200'
      traefik.docker.network: '{{ traefik_network }}'
    state: present
    restart_policy: unless-stopped