# Deploy Grocy
# ----------------
- name: Deploy Grocy
  community.docker.docker_container:
    name: grocy
    image: 'lscr.io/linuxserver/grocy'
    hostname: HomeServer
    env:
      'PUID': '{{ guid }}'
      'PGID': '{{ guid }}'
      'TZ': '{{ timezone }}'
    ports:
      - '9283:80'
    volumes:
      - '{{ config_folder }}/grocy:/config'
    networks:
      - name: '{{ traefik_network }}'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.grocy.entrypoints: 'http'
      traefik.http.routers.grocy.rule: 'Host(`grocy.docker.localhost`)'
      traefik.http.middlewares.grocy-https-redirect.redirectscheme.scheme: 'https'
      traefik.http.routers.grocy.middlewares: 'grocy-https-redirect'
      traefik.http.routers.grocy-secure.entrypoints: 'https'
      traefik.http.routers.grocy-secure.rule: 'Host(`grocy.docker.localhost`)'
      traefik.http.routers.grocy-secure.tls: 'true'
      traefik.http.routers.grocy-secure.service: 'grocy'
      traefik.http.services.grocy.loadbalancer.server.port: '80'
      traefik.docker.network: '{{ traefik_network }}'
    state: present
    restart_policy: unless-stopped