# Deploy Rancher
# --
- name: Deploy Rancher
  community.docker.docker_container:
    name: rancher
    image: 'rancher/rancher'
    env:
      'PUID': '{{ guid }}'
      'PGID': '{{ guid }}'
      'TZ': '{{ timezone }}'
    privileged: yes
    ports:
      - '80:80'
      - '443:443'
    state: present
    restart_policy: unless-stopped