# Remove All Docker Containeirs
# --
- name: Remove Docker Images
  community.docker.docker_image:
    name: '{{ item }}'
    state: absent
  loop:
    - docker.io/traefik:latest
    - ghcr.io/gethomepage/homepage:latest
    - docker.io/portainer/portainer-ce:latest
    - lscr.io/linuxserver/duplicati:2.0.7
    - docker.io/vaultwarden/server:latest
    - lscr.io/linuxserver/syncthing:latest
    # - lscr.io/linuxserver/grocy:latest
    # - docker.io/b4bz/homer:latest
    # - lscr.io/linuxserver/endlessh:latest
    # - docker.io/containrrr/watchtower:latest
    # - docker.io/rancher/rancher:latest