# Start Containeirs
# --
- name: Start Containers
  community.docker.docker_container:
    name: '{{ item }}'
    state: started
  loop:
    - traefik
    - homepage
    - portainer
    - vaultwarden
    - syncthing
    - grocy
    # - homer
    # - endlessh
    # - watchtower
    # - duplicati