# Stop Containeirs
# --
- name: Stop Containers
  community.docker.docker_container:
    name: '{{ item }}'
    state: stopped
  loop:
    - traefik
    - homepage
    - portainer
    - vaultwarden
    - syncthing
    - grocy
    # - homer
    # - endlessh
    # - watchtower
    # - duplicati