# Stop Containeirs
# --
- name: Stop Containers
  community.docker.docker_container:
    name: '{{ item }}'
    state: stopped
  loop:
    - traefik
    - homepage
    - portainer
    - duplicati
    - vaultwarden
    - syncthing
    # - grocy
    # - homer
    # - endlessh
    # - watchtower