# Deploy Watchtower
# --
- name: Deploy Watchtower
  community.docker.docker_container:
    name: watchtower
    image: 'docker.io/containrrr/watchtower'
    env:
      'PUID': '{{ guid }}'
      'PGID': '{{ guid }}'
      'TZ': '{{ timezone }}'
    volumes:
      - '{{ config_folder }}/watchtower/config.json:/config.json'
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - name: '{{ traefik_network }}'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.watchtower.entrypoints: 'http'
      traefik.http.routers.watchtower.rule: 'Host(`watchtower.docker.localhost`)'
      traefik.http.middlewares.watchtower-https-redirect.redirectscheme.scheme: 'https'
      traefik.http.routers.watchtower.middlewares: 'watchtower-https-redirect'
      traefik.http.routers.watchtower-secure.entrypoints: 'https'
      traefik.http.routers.watchtower-secure.rule: 'Host(`watchtower.docker.localhost`)'
      traefik.http.routers.watchtower-secure.tls: 'true'
      traefik.http.routers.watchtower-secure.service: 'watchtower'
      traefik.http.services.watchtower.loadbalancer.server.port: '3080'
      traefik.docker.network: '{{ traefik_network }}'
    state: present
    restart_policy: unless-stopped
